name: CD Python Project

on:
  workflow_dispatch:
    inputs:
      build_path:

        required: true
        default: 'C:\Users\roger\OneDrive\Documentos\ADS\GITHUB\**'
  push:
    branches:
      - main


jobs:

  CriarDiretorio:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'      # nome do arquivo zip
          path: 'C:\Users\roger\OneDrive\Documentos\ADS\GITHUB\**'            # diretório a ser compactado (relativo ao repositório)
          type: zip


  upload:
    needs: CriarDiretorio
    runs-on: windows-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: AULA_DEVOPS/release.zip
          if-no-files-found: error

      - name: Mensagem de sucesso
        run: echo "Upload com sucesso"