name: CD Python Project

on:
  push:
    branches:
      - main

jobs:
  CD:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: AULA_DEVOPS
          if-no-files-found: error

      - name: Mensagem de sucesso
        run: echo "Upload com sucesso"