name: CD Python Project

on:
  push:
    branches:
      - main

jobs:
  CriarDiretorio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          path: |

  upload:
    needs: CriarDiretorio
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: AULA_DEVOPS/release.zip
          if-no-files-found: error

      - name: Mensagem de sucesso
        run: echo "Upload com sucesso"